services:
  nginx:
    container_name: 'event-nginx'
    hostname: 'event-nginx'
    image: 'nginx:1.27.0'
    restart: 'unless-stopped'
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - './_data/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './_data/nginx/conf.d:/etc/nginx/conf.d'
      # - './_data/nginx/certs:/etc/nginx/certs'
    networks:
      - 'event_manager_network'

networks:
  event_manager_network:
    name: 'event_manager_network'
    external: true
