name: Deploy Project

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
        type: string

jobs:
  trigger-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Pipeline
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: frontend.yml
          token: ${{ secrets.GHA_CICD_TOKEN }}
          ref: ${{ inputs.branch }}
          inputs: |
            {"branch": "${{ inputs.branch }}"}

  trigger-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Pipeline
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: backend.yml
          token: ${{ secrets.GHA_CICD_TOKEN }}
          ref: ${{ inputs.branch }}
          inputs: |
            {"branch": "${{ inputs.branch }}"}
