name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: true
        default: 'main'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and run uptime
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem "$EC2_USERNAME@$EC2_HOST" "uptime"
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Checkout this workflow repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 600 key.pem
          echo "SSH key setup complete."
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 host to known hosts
        run: |
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
          echo "EC2 host added to known hosts."
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Pull latest code from GitHub repo
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem "$EC2_USERNAME@$EC2_HOST" << 'EOF'
            set -e
            PROJECT_DIR="/home/ec2-user/event-tickets"

            if [ ! -d "$PROJECT_DIR" ]; then
              echo "Project directory does not exist. Cloning repository..."
              git clone git@github.com:blminh-it/event-manager.git "$PROJECT_DIR"
            fi
            cd "$PROJECT_DIR"
            git pull origin main
          EOF
        env:
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
