name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: true
        default: 'main'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_KNOWN_HOSTS: ${{ secrets.EC2_KNOWN_HOSTS }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    steps:
      - name: Checkout this workflow repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ env.EC2_SSH_KEY }}
          known_hosts: ${{ env.EC2_KNOWN_HOSTS }}

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            echo "Pull repository..."
            cd /home/ec2-user/event-manager
            git checkout ${{ inputs.branch }}
            git pull
